---
- name: Check whether k3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Get k3s node token from server
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  delegate_to: "{{ groups['server'][0] }}"
  register: token_file
  changed_when: false

- name: Set k3s node token fact
  ansible.builtin.set_fact:
    k3s_node_token: "{{ token_file.content | b64decode | trim }}"

- name: Build k3s agent install command
  ansible.builtin.set_fact:
    k3s_agent_install_command: >-
      curl -sfL https://get.k3s.io |
      {% if k3s_version | length > 0 %} INSTALL_K3S_VERSION={{ k3s_version }} {% endif %}
      K3S_URL=https://{{ hostvars[groups['server'][0]].private_ip }}:6443
      K3S_TOKEN={{ k3s_node_token }}
      INSTALL_K3S_EXEC="agent --node-ip {{ private_ip }}"
      sh -

- name: Install k3s agent
  ansible.builtin.shell: "{{ k3s_agent_install_command }}"
  args:
    executable: /bin/bash
  changed_when: true
  when: not k3s_binary.stat.exists
