apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  DATABASE_USER: "taskapp"
  FLASK_ENV: "production"
